# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://xiaoape.github.io
date_format: "ordinal"
title: 小猿杂谈
subtitle: "一路向前莫问前程"
description: "刘鹏的个人博客"
keywords: 杂谈, jack Liu, xiaoape, liupeng
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Liu Peng
organization: 
organization_url: 
github_username: xiaoape
location: NanChang, China
email: liupeng20162341@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xiaoape/xiaoape.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: xiaoape
    repo: blog-comments
    oauth:
        client_id: 6da299130675f46805eb
        client_secret: 19ce174a61a17383a76c548ea061f2bd6ba74621
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: xiaoape
    repo: blog-comments
    clientID: 6da299130675f46805eb
    clientSecret: 19ce174a61a17383a76c548ea061f2bd6ba74621
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
